# This defines the event that triggers the workflow
on:
  push:
    branches:
      - main

jobs:
  # Job 1: Check the code for errors
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # Job 2: Build the website
  build:
    runs-on: ubuntu-latest
    needs: validate  # This ensures build ONLY runs if validate passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
